# Generated by Django 4.1.13 on 2024-03-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_comment_posts_comme_created_aa6d8f_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
