# Generated by Django 4.1.13 on 2024-03-05 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
