# Generated by Django 4.1.13 on 2024-03-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_middle_name_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='type',
        ),
    ]
