# Generated by Django 4.1.13 on 2024-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_additionaluserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='image',
            field=models.ImageField(default='users/default-user-avatar.png', upload_to='users/'),
        ),
    ]
