# Generated by Django 4.1.13 on 2024-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_additionaluserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default-user-avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
