# Generated by Django 4.1.13 on 2024-03-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='image',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default-user-avatar.png', null=True, upload_to='users/avatars/'),
        ),
    ]
